apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsplassen-metrics-api
  namespace: arbeidsplassen
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 15
  readiness:
    path: /internal/isReady
    initialDelay: 15
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
  ingresses:
    {{ #each ingresses as |url| }}
      - {{url}}
    {{/each}}
  gcp:
    bigQueryDatasets:
      - name: arbeidsplassen_metrics
        permission: READWRITE
  env:
    - name: BQ_DATASET_ID
      value: arbeidsplassen_metrics
