name: build-deploy-dev
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
      - ".github/dependabot.yml"
      - ".github/workflows/dependabot-auto-merge.yml"
    branches:
      - '**'

jobs:
  call-workflow:
    permissions:
      actions: read
      contents: write
      security-events: write
      id-token: write
    if: "(github.ref_name == 'main') || contains(github.event.head_commit.message, 'deploy:dev')"
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v7
    with:
      TEAM: arbeidsplassen
      BUILD_CACHE: maven
      NAIS_RESOURCE: .nais/nais.yaml
      NAIS_VARS: .nais/dev.yaml
      JAVA_VERSION: 25
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'main' }}
